//! The single source of truth for the panel's HTTP surface.
//!
//! `ROUTE_TABLE` describes every method+path pair exactly once. The axum router
//! in `panel-app` is built from it, and the `GET /api/ui/contracts` document is
//! generated from it. There is no second route list in the project, so a
//! divergence between what is served and what is advertised to the frontend has
//! nowhere to be expressed.
//!
//! Adding a route takes three edits: a new `RouteId` variant, a `ROUTE_TABLE`
//! row, and an arm in `method_router` (panel-app). Skipping any of them is a
//! compile error or a failing test, never a silent drift.
//!
//! `exposure` is a trust boundary, not decoration. It is assigned from the
//! authentication a route actually enforces, never from its path prefix:
//! `/api/installer/jobs/result` sits in the `Installer` group but authenticates
//! with an executor token in the request body, so its exposure is `Executor` and
//! it stays out of the browser contract.

use serde::{Deserialize, Serialize};

/// HTTP method. A local type so `panel-core` does not depend on axum or http:
/// the core stays transport-agnostic and the mapping lives in `panel-app`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum RouteMethod {
    Get,
    Post,
    Put,
    Delete,
}

impl RouteMethod {
    pub const ALL: &'static [Self] = &[Self::Get, Self::Post, Self::Put, Self::Delete];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Put => "PUT",
            Self::Delete => "DELETE",
        }
    }
}

/// Functional group of a route. Answers "what is this endpoint about" and drives
/// frontend navigation and the split of the contract document.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteGroup {
    Ui,
    Security,
    Core,
    Users,
    Network,
    Clusters,
    Nodes,
    Provisioning,
    SubscriptionCatalog,
    Telegram,
    System,
    Installer,
    RouteMaterials,
    NodeAgent,
    Public,
}

impl RouteGroup {
    pub const ALL: &'static [Self] = &[
        Self::Ui,
        Self::Security,
        Self::Core,
        Self::Users,
        Self::Network,
        Self::Clusters,
        Self::Nodes,
        Self::Provisioning,
        Self::SubscriptionCatalog,
        Self::Telegram,
        Self::System,
        Self::Installer,
        Self::RouteMaterials,
        Self::NodeAgent,
        Self::Public,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ui => "ui",
            Self::Security => "security",
            Self::Core => "core",
            Self::Users => "users",
            Self::Network => "network",
            Self::Clusters => "clusters",
            Self::Nodes => "nodes",
            Self::Provisioning => "provisioning",
            Self::SubscriptionCatalog => "subscription_catalog",
            Self::Telegram => "telegram",
            Self::System => "system",
            Self::Installer => "installer",
            Self::RouteMaterials => "route_materials",
            Self::NodeAgent => "node_agent",
            Self::Public => "public",
        }
    }
}

/// Trust boundary: who may call a route and what they authenticate with.
///
/// - `AdminUi`   — an admin session (`authorize`); this is the browser surface;
/// - `NodeAgent` — a node token in the `x-hydra-node-token` header;
/// - `Executor`  — a provisioning or installer executor token, in a header or body;
/// - `Public`    — no authentication, reachable from the internet;
/// - `Debug`     — diagnostic; must not exist in a production build.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteExposure {
    AdminUi,
    NodeAgent,
    Executor,
    Public,
    Debug,
}

impl RouteExposure {
    pub const ALL: &'static [Self] = &[
        Self::AdminUi,
        Self::NodeAgent,
        Self::Executor,
        Self::Public,
        Self::Debug,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AdminUi => "admin_ui",
            Self::NodeAgent => "node_agent",
            Self::Executor => "executor",
            Self::Public => "public",
            Self::Debug => "debug",
        }
    }
}

/// Route identifier.
///
/// Exists for the exhaustive `match` in `panel-app`: a table row without a bound
/// handler fails to compile. The same check is impossible over `&'static str`,
/// because a `match` on a string requires a `_` arm.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RouteId {
    Root,
    DashboardGet,
    DashboardSlash,
    Health,
    PublicSubscription,
    PublicDeviceSubscription,
    ExchangeSubscriptionDeviceEnrollment,
    Login,
    Logout,
    Me,
    GetAdminSessions,
    RevokeAdminSession,
    GetUiBootstrap,
    GetUiOverview,
    GetUiContracts,
    GetUiSecurity,
    GetUiCore,
    GetUiUsersSummary,
    GetUiNodesSummary,
    GetUiClustersSummary,
    GetUiTelegramSummary,
    GetUiAuditSummary,
    GetUiSubscriptionsSummary,
    GetUiProtocolsSummary,
    GetUiInstallerSummary,
    GetSecuritySettings,
    UpdateSecuritySettings,
    ApplySecurityPreset,
    GetTwoFactorState,
    SetupTwoFactor,
    EnableTwoFactor,
    DisableTwoFactor,
    UpdateTwoFactorTwoStep,
    GetActiveBans,
    CreateBan,
    RemoveBan,
    GetSecurityAudit,
    GetSecurityStatus,
    GetTelegramSettings,
    UpdateTelegramSettings,
    GetTelegramEvents,
    RetryDueTelegramEvents,
    SendTelegramTest,
    GetPanelAccessModes,
    PlanPanelInstall,
    CreatePanelInstallerBootstrap,
    CreatePanelInstallerSession,
    ReportPanelInstallerResult,
    ListPanelInstallerJobs,
    CreatePanelInstallerJob,
    ReportPanelInstallerJobHeartbeat,
    GetPanelInstallerJobForExecutor,
    ReportPanelInstallerJobResult,
    GetSystemOverview,
    GetResourceBudget,
    GetSystemThresholds,
    UpdateSystemThresholds,
    GetSecretKeyReadiness,
    GetSystemAlerts,
    GetSystemAlertHistory,
    GetOperationalLogs,
    GetCoreConfig,
    SaveCoreConfig,
    GetGeneratedCoreConfig,
    GetGeneratedXrayConfig,
    GetGeneratedXrayConfigValidation,
    GetGeneratedXrayConfigExternalValidation,
    GetCoreState,
    GetRouteMaterials,
    RotateRouteCredential,
    RevokeRouteCredential,
    RotateRouteCa,
    ApplyGeneratedCoreConfig,
    GetCoreApplyHistory,
    ExecuteCoreAction,
    RestartCore,
    UpdateXrayCore,
    ListUsers,
    CreateUser,
    GetUsersActivity,
    GetUser,
    UpdateUser,
    DeleteUser,
    ResetUserUsage,
    ReportUserUsage,
    GetUserActivity,
    RevokeUserSubscription,
    GetUserSubscription,
    RenderUserSubscription,
    GetUserConfigPreview,
    GetGeneratedUserConfig,
    ListUserTemplates,
    CreateUserTemplate,
    UpdateUserTemplate,
    DeleteUserTemplate,
    ListSubscriptionPlans,
    CreateSubscriptionPlan,
    GetSubscriptionPlan,
    UpdateSubscriptionPlan,
    DeleteSubscriptionPlan,
    ListSubscriptionPlanClients,
    CreateSubscriptionClient,
    GetSubscriptionClient,
    UpdateSubscriptionClient,
    DeleteSubscriptionClient,
    RenderSubscriptionClient,
    GetSubscriptionClientAccessPreview,
    UpdateSubscriptionClientAccess,
    ListSubscriptionClientDevices,
    ListSubscriptionDeviceEnrollments,
    CreateSubscriptionDeviceEnrollment,
    RevokeSubscriptionDeviceEnrollment,
    RegisterSubscriptionClientDevice,
    RevokeSubscriptionClientDevice,
    ListSubscriptionClientSessions,
    GetSubscriptionClientUsage,
    ReportSubscriptionClientUsage,
    ResetSubscriptionClientUsage,
    RevokeSubscriptionClient,
    ListInbounds,
    CreateInbound,
    GetProtocolCapabilities,
    UpdateInbound,
    DeleteInbound,
    ListHosts,
    CreateHost,
    UpdateHost,
    DeleteHost,
    ListProxyProfiles,
    CreateProxyProfile,
    UpdateProxyProfile,
    DeleteProxyProfile,
    ListClusters,
    CreateCluster,
    UpdateCluster,
    DeleteCluster,
    ValidateCluster,
    PreviewCluster,
    ListNodes,
    CreateNode,
    GetNodeHealthCenter,
    UpdateNode,
    DeleteNode,
    GetNodeDiagnostics,
    GetNodeApplyStatus,
    ListNodeProvisioningTasks,
    GetNodeProvisioningStatus,
    GetNodeProvisioningEvents,
    GetNodeProvisioningPreflight,
    GetNodeProvisioningSshPreflightProbe,
    GetNodeProvisioningSshInstallPlan,
    NodeProvisioningExecutorHandshake,
    ListNodeProvisioningExecutors,
    ListNodeProvisioningExecutorSubmissions,
    UpdateNodeProvisioningExecutorTrust,
    RotateNodeProvisioningExecutorToken,
    GetNodeProvisioningExecutorSession,
    StartNodeProvisioning,
    ReprovisionNode,
    UpdateNodeProvisioningStep,
    ReportNodeProvisioningCommand,
    ReportNodeProvisioningHandoff,
    TouchNodeProvisioningTask,
    FinishNodeProvisioning,
    RetryNodeProvisioning,
    GetNodeBootstrapReadiness,
    RunNodeBootstrapProbe,
    GetNodeBootstrapHistory,
    RotateNodeAuthToken,
    RequestNodeApply,
    RetryNodeApply,
    RequestNodeRollback,
    GetNodeClusterTargets,
    GetNodeLocalHealth,
    GetNodeLocalState,
    ExecuteNodeLocalRuntimeAction,
    ExecuteNodeLocalRuntimeComponentAction,
    UpdateNodeLocalXray,
    RecordNodeHeartbeat,
    UpdateNodeSyncStatus,
    GetNodeSyncHistory,
    GetNodeApplyResults,
    NodeAgentMe,
    NodeAgentConfig,
    NodeAgentXrayConfig,
    NodeAgentRouteCredentials,
    NodeAgentClusterTargets,
    NodeAgentHeartbeat,
    NodeAgentSync,
    NodeAgentApplyResult,
    NodeAgentLogs,
    NodeAgentMetrics,
    NodeAgentSubscriptionClientUsageReport,
    NodeAgentSubscriptionSessionsReport,
    NodeAgentSubscriptionSessionEnforcementResult,
}

impl RouteId {
    pub const ALL: &'static [Self] = &[
        Self::Root,
        Self::DashboardGet,
        Self::DashboardSlash,
        Self::Health,
        Self::PublicSubscription,
        Self::PublicDeviceSubscription,
        Self::ExchangeSubscriptionDeviceEnrollment,
        Self::Login,
        Self::Logout,
        Self::Me,
        Self::GetAdminSessions,
        Self::RevokeAdminSession,
        Self::GetUiBootstrap,
        Self::GetUiOverview,
        Self::GetUiContracts,
        Self::GetUiSecurity,
        Self::GetUiCore,
        Self::GetUiUsersSummary,
        Self::GetUiNodesSummary,
        Self::GetUiClustersSummary,
        Self::GetUiTelegramSummary,
        Self::GetUiAuditSummary,
        Self::GetUiSubscriptionsSummary,
        Self::GetUiProtocolsSummary,
        Self::GetUiInstallerSummary,
        Self::GetSecuritySettings,
        Self::UpdateSecuritySettings,
        Self::ApplySecurityPreset,
        Self::GetTwoFactorState,
        Self::SetupTwoFactor,
        Self::EnableTwoFactor,
        Self::DisableTwoFactor,
        Self::UpdateTwoFactorTwoStep,
        Self::GetActiveBans,
        Self::CreateBan,
        Self::RemoveBan,
        Self::GetSecurityAudit,
        Self::GetSecurityStatus,
        Self::GetTelegramSettings,
        Self::UpdateTelegramSettings,
        Self::GetTelegramEvents,
        Self::RetryDueTelegramEvents,
        Self::SendTelegramTest,
        Self::GetPanelAccessModes,
        Self::PlanPanelInstall,
        Self::CreatePanelInstallerBootstrap,
        Self::CreatePanelInstallerSession,
        Self::ReportPanelInstallerResult,
        Self::ListPanelInstallerJobs,
        Self::CreatePanelInstallerJob,
        Self::ReportPanelInstallerJobHeartbeat,
        Self::GetPanelInstallerJobForExecutor,
        Self::ReportPanelInstallerJobResult,
        Self::GetSystemOverview,
        Self::GetResourceBudget,
        Self::GetSystemThresholds,
        Self::UpdateSystemThresholds,
        Self::GetSecretKeyReadiness,
        Self::GetSystemAlerts,
        Self::GetSystemAlertHistory,
        Self::GetOperationalLogs,
        Self::GetCoreConfig,
        Self::SaveCoreConfig,
        Self::GetGeneratedCoreConfig,
        Self::GetGeneratedXrayConfig,
        Self::GetGeneratedXrayConfigValidation,
        Self::GetGeneratedXrayConfigExternalValidation,
        Self::GetCoreState,
        Self::GetRouteMaterials,
        Self::RotateRouteCredential,
        Self::RevokeRouteCredential,
        Self::RotateRouteCa,
        Self::ApplyGeneratedCoreConfig,
        Self::GetCoreApplyHistory,
        Self::ExecuteCoreAction,
        Self::RestartCore,
        Self::UpdateXrayCore,
        Self::ListUsers,
        Self::CreateUser,
        Self::GetUsersActivity,
        Self::GetUser,
        Self::UpdateUser,
        Self::DeleteUser,
        Self::ResetUserUsage,
        Self::ReportUserUsage,
        Self::GetUserActivity,
        Self::RevokeUserSubscription,
        Self::GetUserSubscription,
        Self::RenderUserSubscription,
        Self::GetUserConfigPreview,
        Self::GetGeneratedUserConfig,
        Self::ListUserTemplates,
        Self::CreateUserTemplate,
        Self::UpdateUserTemplate,
        Self::DeleteUserTemplate,
        Self::ListSubscriptionPlans,
        Self::CreateSubscriptionPlan,
        Self::GetSubscriptionPlan,
        Self::UpdateSubscriptionPlan,
        Self::DeleteSubscriptionPlan,
        Self::ListSubscriptionPlanClients,
        Self::CreateSubscriptionClient,
        Self::GetSubscriptionClient,
        Self::UpdateSubscriptionClient,
        Self::DeleteSubscriptionClient,
        Self::RenderSubscriptionClient,
        Self::GetSubscriptionClientAccessPreview,
        Self::UpdateSubscriptionClientAccess,
        Self::ListSubscriptionClientDevices,
        Self::ListSubscriptionDeviceEnrollments,
        Self::CreateSubscriptionDeviceEnrollment,
        Self::RevokeSubscriptionDeviceEnrollment,
        Self::RegisterSubscriptionClientDevice,
        Self::RevokeSubscriptionClientDevice,
        Self::ListSubscriptionClientSessions,
        Self::GetSubscriptionClientUsage,
        Self::ReportSubscriptionClientUsage,
        Self::ResetSubscriptionClientUsage,
        Self::RevokeSubscriptionClient,
        Self::ListInbounds,
        Self::CreateInbound,
        Self::GetProtocolCapabilities,
        Self::UpdateInbound,
        Self::DeleteInbound,
        Self::ListHosts,
        Self::CreateHost,
        Self::UpdateHost,
        Self::DeleteHost,
        Self::ListProxyProfiles,
        Self::CreateProxyProfile,
        Self::UpdateProxyProfile,
        Self::DeleteProxyProfile,
        Self::ListClusters,
        Self::CreateCluster,
        Self::UpdateCluster,
        Self::DeleteCluster,
        Self::ValidateCluster,
        Self::PreviewCluster,
        Self::ListNodes,
        Self::CreateNode,
        Self::GetNodeHealthCenter,
        Self::UpdateNode,
        Self::DeleteNode,
        Self::GetNodeDiagnostics,
        Self::GetNodeApplyStatus,
        Self::ListNodeProvisioningTasks,
        Self::GetNodeProvisioningStatus,
        Self::GetNodeProvisioningEvents,
        Self::GetNodeProvisioningPreflight,
        Self::GetNodeProvisioningSshPreflightProbe,
        Self::GetNodeProvisioningSshInstallPlan,
        Self::NodeProvisioningExecutorHandshake,
        Self::ListNodeProvisioningExecutors,
        Self::ListNodeProvisioningExecutorSubmissions,
        Self::UpdateNodeProvisioningExecutorTrust,
        Self::RotateNodeProvisioningExecutorToken,
        Self::GetNodeProvisioningExecutorSession,
        Self::StartNodeProvisioning,
        Self::ReprovisionNode,
        Self::UpdateNodeProvisioningStep,
        Self::ReportNodeProvisioningCommand,
        Self::ReportNodeProvisioningHandoff,
        Self::TouchNodeProvisioningTask,
        Self::FinishNodeProvisioning,
        Self::RetryNodeProvisioning,
        Self::GetNodeBootstrapReadiness,
        Self::RunNodeBootstrapProbe,
        Self::GetNodeBootstrapHistory,
        Self::RotateNodeAuthToken,
        Self::RequestNodeApply,
        Self::RetryNodeApply,
        Self::RequestNodeRollback,
        Self::GetNodeClusterTargets,
        Self::GetNodeLocalHealth,
        Self::GetNodeLocalState,
        Self::ExecuteNodeLocalRuntimeAction,
        Self::ExecuteNodeLocalRuntimeComponentAction,
        Self::UpdateNodeLocalXray,
        Self::RecordNodeHeartbeat,
        Self::UpdateNodeSyncStatus,
        Self::GetNodeSyncHistory,
        Self::GetNodeApplyResults,
        Self::NodeAgentMe,
        Self::NodeAgentConfig,
        Self::NodeAgentXrayConfig,
        Self::NodeAgentRouteCredentials,
        Self::NodeAgentClusterTargets,
        Self::NodeAgentHeartbeat,
        Self::NodeAgentSync,
        Self::NodeAgentApplyResult,
        Self::NodeAgentLogs,
        Self::NodeAgentMetrics,
        Self::NodeAgentSubscriptionClientUsageReport,
        Self::NodeAgentSubscriptionSessionsReport,
        Self::NodeAgentSubscriptionSessionEnforcementResult,
    ];
}

/// One method+path pair.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RouteSpec {
    pub id: RouteId,
    pub method: RouteMethod,
    pub path: &'static str,
    pub group: RouteGroup,
    pub exposure: RouteExposure,
    /// Accepts `?limit=` and returns a truncated list, so the frontend can tell
    /// where a list is bounded and needs paging rather than showing everything.
    pub paginated: bool,
}

pub const ROUTE_TABLE: &[RouteSpec] = &[
    RouteSpec {
        id: RouteId::Root,
        method: RouteMethod::Get,
        path: "/",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DashboardGet,
        method: RouteMethod::Get,
        path: "/dashboard",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DashboardSlash,
        method: RouteMethod::Get,
        path: "/dashboard/",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::Health,
        method: RouteMethod::Get,
        path: "/health",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::PublicSubscription,
        method: RouteMethod::Get,
        path: "/sub/{subscription_token}",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::PublicDeviceSubscription,
        method: RouteMethod::Get,
        path: "/sub/device/{device_credential}",
        group: RouteGroup::Public,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ExchangeSubscriptionDeviceEnrollment,
        method: RouteMethod::Post,
        path: "/api/device-enrollment/exchange",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::Login,
        method: RouteMethod::Post,
        path: "/api/admin/login",
        group: RouteGroup::Security,
        exposure: RouteExposure::Public,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::Logout,
        method: RouteMethod::Post,
        path: "/api/admin/logout",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::Me,
        method: RouteMethod::Get,
        path: "/api/admin/me",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetAdminSessions,
        method: RouteMethod::Get,
        path: "/api/admin/sessions",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RevokeAdminSession,
        method: RouteMethod::Post,
        path: "/api/admin/sessions/{session_id}/revoke",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiBootstrap,
        method: RouteMethod::Get,
        path: "/api/ui/bootstrap",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiOverview,
        method: RouteMethod::Get,
        path: "/api/ui/overview",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiContracts,
        method: RouteMethod::Get,
        path: "/api/ui/contracts",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiSecurity,
        method: RouteMethod::Get,
        path: "/api/ui/security",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiCore,
        method: RouteMethod::Get,
        path: "/api/ui/core",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiUsersSummary,
        method: RouteMethod::Get,
        path: "/api/ui/users",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiNodesSummary,
        method: RouteMethod::Get,
        path: "/api/ui/nodes",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiClustersSummary,
        method: RouteMethod::Get,
        path: "/api/ui/clusters",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiTelegramSummary,
        method: RouteMethod::Get,
        path: "/api/ui/telegram",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiAuditSummary,
        method: RouteMethod::Get,
        path: "/api/ui/audit",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiSubscriptionsSummary,
        method: RouteMethod::Get,
        path: "/api/ui/subscriptions",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiProtocolsSummary,
        method: RouteMethod::Get,
        path: "/api/ui/protocols",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUiInstallerSummary,
        method: RouteMethod::Get,
        path: "/api/ui/installer",
        group: RouteGroup::Ui,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSecuritySettings,
        method: RouteMethod::Get,
        path: "/api/admin/security/settings",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateSecuritySettings,
        method: RouteMethod::Put,
        path: "/api/admin/security/settings",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ApplySecurityPreset,
        method: RouteMethod::Post,
        path: "/api/admin/security/preset",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetTwoFactorState,
        method: RouteMethod::Get,
        path: "/api/admin/2fa/state",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::SetupTwoFactor,
        method: RouteMethod::Post,
        path: "/api/admin/2fa/setup",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::EnableTwoFactor,
        method: RouteMethod::Post,
        path: "/api/admin/2fa/enable",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DisableTwoFactor,
        method: RouteMethod::Post,
        path: "/api/admin/2fa/disable",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateTwoFactorTwoStep,
        method: RouteMethod::Post,
        path: "/api/admin/2fa/two-step",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetActiveBans,
        method: RouteMethod::Get,
        path: "/api/admin/security/bans",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateBan,
        method: RouteMethod::Post,
        path: "/api/admin/security/bans",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RemoveBan,
        method: RouteMethod::Post,
        path: "/api/admin/security/bans/{client_ip}",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSecurityAudit,
        method: RouteMethod::Get,
        path: "/api/admin/security/audit",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetSecurityStatus,
        method: RouteMethod::Get,
        path: "/api/admin/security/status",
        group: RouteGroup::Security,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetTelegramSettings,
        method: RouteMethod::Get,
        path: "/api/telegram/settings",
        group: RouteGroup::Telegram,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateTelegramSettings,
        method: RouteMethod::Put,
        path: "/api/telegram/settings",
        group: RouteGroup::Telegram,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetTelegramEvents,
        method: RouteMethod::Get,
        path: "/api/telegram/events",
        group: RouteGroup::Telegram,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::RetryDueTelegramEvents,
        method: RouteMethod::Post,
        path: "/api/telegram/retry-due",
        group: RouteGroup::Telegram,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::SendTelegramTest,
        method: RouteMethod::Post,
        path: "/api/telegram/test",
        group: RouteGroup::Telegram,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetPanelAccessModes,
        method: RouteMethod::Get,
        path: "/api/installer/access-modes",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::PlanPanelInstall,
        method: RouteMethod::Post,
        path: "/api/installer/plan",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreatePanelInstallerBootstrap,
        method: RouteMethod::Post,
        path: "/api/installer/bootstrap",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreatePanelInstallerSession,
        method: RouteMethod::Post,
        path: "/api/installer/session",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportPanelInstallerResult,
        method: RouteMethod::Post,
        path: "/api/installer/session/result",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListPanelInstallerJobs,
        method: RouteMethod::Get,
        path: "/api/installer/jobs",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreatePanelInstallerJob,
        method: RouteMethod::Post,
        path: "/api/installer/jobs",
        group: RouteGroup::Installer,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportPanelInstallerJobHeartbeat,
        method: RouteMethod::Post,
        path: "/api/installer/jobs/heartbeat",
        group: RouteGroup::Installer,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetPanelInstallerJobForExecutor,
        method: RouteMethod::Post,
        path: "/api/installer/jobs/executor-session",
        group: RouteGroup::Installer,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportPanelInstallerJobResult,
        method: RouteMethod::Post,
        path: "/api/installer/jobs/result",
        group: RouteGroup::Installer,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSystemOverview,
        method: RouteMethod::Get,
        path: "/api/system/overview",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetResourceBudget,
        method: RouteMethod::Get,
        path: "/api/system/resource-budget",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSystemThresholds,
        method: RouteMethod::Get,
        path: "/api/system/thresholds",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateSystemThresholds,
        method: RouteMethod::Put,
        path: "/api/system/thresholds",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSecretKeyReadiness,
        method: RouteMethod::Get,
        path: "/api/system/secret-readiness",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSystemAlerts,
        method: RouteMethod::Get,
        path: "/api/system/alerts",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSystemAlertHistory,
        method: RouteMethod::Get,
        path: "/api/system/alerts/history",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetOperationalLogs,
        method: RouteMethod::Get,
        path: "/api/system/logs",
        group: RouteGroup::System,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetCoreConfig,
        method: RouteMethod::Get,
        path: "/api/core/config",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::SaveCoreConfig,
        method: RouteMethod::Put,
        path: "/api/core/config",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetGeneratedCoreConfig,
        method: RouteMethod::Get,
        path: "/api/core/generated-config",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetGeneratedXrayConfig,
        method: RouteMethod::Get,
        path: "/api/core/xray-config",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetGeneratedXrayConfigValidation,
        method: RouteMethod::Get,
        path: "/api/core/xray-config/validation",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetGeneratedXrayConfigExternalValidation,
        method: RouteMethod::Get,
        path: "/api/core/xray-config/external-validation",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetCoreState,
        method: RouteMethod::Get,
        path: "/api/core/state",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetRouteMaterials,
        method: RouteMethod::Get,
        path: "/api/route-materials",
        group: RouteGroup::RouteMaterials,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RotateRouteCredential,
        method: RouteMethod::Post,
        path: "/api/route-materials/credentials/rotate",
        group: RouteGroup::RouteMaterials,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RevokeRouteCredential,
        method: RouteMethod::Post,
        path: "/api/route-materials/credentials/revoke",
        group: RouteGroup::RouteMaterials,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RotateRouteCa,
        method: RouteMethod::Post,
        path: "/api/route-materials/ca/rotate",
        group: RouteGroup::RouteMaterials,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ApplyGeneratedCoreConfig,
        method: RouteMethod::Post,
        path: "/api/core/apply-generated",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetCoreApplyHistory,
        method: RouteMethod::Get,
        path: "/api/core/apply-history",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::ExecuteCoreAction,
        method: RouteMethod::Post,
        path: "/api/core/actions",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RestartCore,
        method: RouteMethod::Post,
        path: "/api/core/restart",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateXrayCore,
        method: RouteMethod::Post,
        path: "/api/core/xray/update",
        group: RouteGroup::Core,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListUsers,
        method: RouteMethod::Get,
        path: "/api/users",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::CreateUser,
        method: RouteMethod::Post,
        path: "/api/users",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUsersActivity,
        method: RouteMethod::Get,
        path: "/api/users/activity",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetUser,
        method: RouteMethod::Get,
        path: "/api/users/{username}",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateUser,
        method: RouteMethod::Put,
        path: "/api/users/{username}",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteUser,
        method: RouteMethod::Delete,
        path: "/api/users/{username}",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ResetUserUsage,
        method: RouteMethod::Post,
        path: "/api/users/{username}/usage/reset",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportUserUsage,
        method: RouteMethod::Post,
        path: "/api/users/{username}/usage/report",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUserActivity,
        method: RouteMethod::Get,
        path: "/api/users/{username}/activity",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::RevokeUserSubscription,
        method: RouteMethod::Post,
        path: "/api/users/{username}/subscription/revoke",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUserSubscription,
        method: RouteMethod::Get,
        path: "/api/users/{username}/subscription",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RenderUserSubscription,
        method: RouteMethod::Get,
        path: "/api/users/{username}/subscription/render",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetUserConfigPreview,
        method: RouteMethod::Get,
        path: "/api/users/{username}/config-preview",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetGeneratedUserConfig,
        method: RouteMethod::Get,
        path: "/api/users/{username}/generated-config",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListUserTemplates,
        method: RouteMethod::Get,
        path: "/api/user-templates",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateUserTemplate,
        method: RouteMethod::Post,
        path: "/api/user-templates",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateUserTemplate,
        method: RouteMethod::Put,
        path: "/api/user-templates/{template_id}",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteUserTemplate,
        method: RouteMethod::Delete,
        path: "/api/user-templates/{template_id}",
        group: RouteGroup::Users,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListSubscriptionPlans,
        method: RouteMethod::Get,
        path: "/api/subscription-plans",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::CreateSubscriptionPlan,
        method: RouteMethod::Post,
        path: "/api/subscription-plans",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSubscriptionPlan,
        method: RouteMethod::Get,
        path: "/api/subscription-plans/{plan_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateSubscriptionPlan,
        method: RouteMethod::Put,
        path: "/api/subscription-plans/{plan_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteSubscriptionPlan,
        method: RouteMethod::Delete,
        path: "/api/subscription-plans/{plan_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListSubscriptionPlanClients,
        method: RouteMethod::Get,
        path: "/api/subscription-plans/{plan_id}/clients",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::CreateSubscriptionClient,
        method: RouteMethod::Post,
        path: "/api/subscription-plans/{plan_id}/clients",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSubscriptionClient,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateSubscriptionClient,
        method: RouteMethod::Put,
        path: "/api/subscription-clients/{client_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteSubscriptionClient,
        method: RouteMethod::Delete,
        path: "/api/subscription-clients/{client_id}",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RenderSubscriptionClient,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/subscription/render",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetSubscriptionClientAccessPreview,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/access-preview",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateSubscriptionClientAccess,
        method: RouteMethod::Put,
        path: "/api/subscription-clients/{client_id}/node-access",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListSubscriptionClientDevices,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/devices",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::ListSubscriptionDeviceEnrollments,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/device-enrollments",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::CreateSubscriptionDeviceEnrollment,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/device-enrollments",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RevokeSubscriptionDeviceEnrollment,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/device-enrollments/{grant_id}/revoke",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RegisterSubscriptionClientDevice,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/devices/register",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RevokeSubscriptionClientDevice,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/devices/{device_id}/revoke",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListSubscriptionClientSessions,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/sessions",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetSubscriptionClientUsage,
        method: RouteMethod::Get,
        path: "/api/subscription-clients/{client_id}/usage",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportSubscriptionClientUsage,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/usage",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ResetSubscriptionClientUsage,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/usage/reset",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RevokeSubscriptionClient,
        method: RouteMethod::Post,
        path: "/api/subscription-clients/{client_id}/revoke",
        group: RouteGroup::SubscriptionCatalog,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListInbounds,
        method: RouteMethod::Get,
        path: "/api/inbounds",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateInbound,
        method: RouteMethod::Post,
        path: "/api/inbounds",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetProtocolCapabilities,
        method: RouteMethod::Get,
        path: "/api/protocol-capabilities",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateInbound,
        method: RouteMethod::Put,
        path: "/api/inbounds/{tag}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteInbound,
        method: RouteMethod::Delete,
        path: "/api/inbounds/{tag}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListHosts,
        method: RouteMethod::Get,
        path: "/api/hosts",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateHost,
        method: RouteMethod::Post,
        path: "/api/hosts",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateHost,
        method: RouteMethod::Put,
        path: "/api/hosts/{host_id}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteHost,
        method: RouteMethod::Delete,
        path: "/api/hosts/{host_id}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListProxyProfiles,
        method: RouteMethod::Get,
        path: "/api/proxy-profiles",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateProxyProfile,
        method: RouteMethod::Post,
        path: "/api/proxy-profiles",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateProxyProfile,
        method: RouteMethod::Put,
        path: "/api/proxy-profiles/{profile_id}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteProxyProfile,
        method: RouteMethod::Delete,
        path: "/api/proxy-profiles/{profile_id}",
        group: RouteGroup::Network,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListClusters,
        method: RouteMethod::Get,
        path: "/api/clusters",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateCluster,
        method: RouteMethod::Post,
        path: "/api/clusters",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateCluster,
        method: RouteMethod::Put,
        path: "/api/clusters/{cluster_id}",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteCluster,
        method: RouteMethod::Delete,
        path: "/api/clusters/{cluster_id}",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ValidateCluster,
        method: RouteMethod::Get,
        path: "/api/clusters/{cluster_id}/validation",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::PreviewCluster,
        method: RouteMethod::Get,
        path: "/api/clusters/{cluster_id}/preview",
        group: RouteGroup::Clusters,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListNodes,
        method: RouteMethod::Get,
        path: "/api/nodes",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::CreateNode,
        method: RouteMethod::Post,
        path: "/api/nodes",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeHealthCenter,
        method: RouteMethod::Get,
        path: "/api/nodes/health-center",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateNode,
        method: RouteMethod::Put,
        path: "/api/nodes/{node_id}",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::DeleteNode,
        method: RouteMethod::Delete,
        path: "/api/nodes/{node_id}",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeDiagnostics,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/diagnostics",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeApplyStatus,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/apply-status",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListNodeProvisioningTasks,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningStatus,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/status",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningEvents,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/events",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningPreflight,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/preflight",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningSshPreflightProbe,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/ssh-preflight-probe",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningSshInstallPlan,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/ssh-install-plan",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeProvisioningExecutorHandshake,
        method: RouteMethod::Post,
        path: "/api/provisioning/executor-handshake",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListNodeProvisioningExecutors,
        method: RouteMethod::Get,
        path: "/api/provisioning/executors",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ListNodeProvisioningExecutorSubmissions,
        method: RouteMethod::Get,
        path: "/api/provisioning/executor-submissions",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::UpdateNodeProvisioningExecutorTrust,
        method: RouteMethod::Put,
        path: "/api/provisioning/executors/{executor_id}/trust",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RotateNodeProvisioningExecutorToken,
        method: RouteMethod::Post,
        path: "/api/provisioning/executors/{executor_id}/auth/rotate",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeProvisioningExecutorSession,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/executor-session",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::StartNodeProvisioning,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/start",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReprovisionNode,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/reprovision",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateNodeProvisioningStep,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/step",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportNodeProvisioningCommand,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/command-report",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ReportNodeProvisioningHandoff,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/handoff",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::Executor,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::TouchNodeProvisioningTask,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/touch",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::FinishNodeProvisioning,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/finish",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RetryNodeProvisioning,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/provisioning/{task_id}/retry",
        group: RouteGroup::Provisioning,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeBootstrapReadiness,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/bootstrap-readiness",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RunNodeBootstrapProbe,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/bootstrap-probe",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeBootstrapHistory,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/bootstrap-history",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::RotateNodeAuthToken,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/auth/rotate",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RequestNodeApply,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/apply",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RetryNodeApply,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/apply/retry",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RequestNodeRollback,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/rollback",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeClusterTargets,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/cluster-targets",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeLocalHealth,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/local/health",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeLocalState,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/local/state",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ExecuteNodeLocalRuntimeAction,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/local/runtime/{action}",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::ExecuteNodeLocalRuntimeComponentAction,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/local/runtime-components/{component}/{action}",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateNodeLocalXray,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/local/xray/update",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::RecordNodeHeartbeat,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/heartbeat",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::UpdateNodeSyncStatus,
        method: RouteMethod::Post,
        path: "/api/nodes/{node_id}/sync",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::GetNodeSyncHistory,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/sync-history",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::GetNodeApplyResults,
        method: RouteMethod::Get,
        path: "/api/nodes/{node_id}/apply-results",
        group: RouteGroup::Nodes,
        exposure: RouteExposure::AdminUi,
        paginated: true,
    },
    RouteSpec {
        id: RouteId::NodeAgentMe,
        method: RouteMethod::Get,
        path: "/api/node-agent/me",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentConfig,
        method: RouteMethod::Get,
        path: "/api/node-agent/config",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentXrayConfig,
        method: RouteMethod::Get,
        path: "/api/node-agent/xray-config",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentRouteCredentials,
        method: RouteMethod::Get,
        path: "/api/node-agent/route-credentials",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentClusterTargets,
        method: RouteMethod::Get,
        path: "/api/node-agent/cluster-targets",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentHeartbeat,
        method: RouteMethod::Post,
        path: "/api/node-agent/heartbeat",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentSync,
        method: RouteMethod::Post,
        path: "/api/node-agent/sync",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentApplyResult,
        method: RouteMethod::Post,
        path: "/api/node-agent/apply-result",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentLogs,
        method: RouteMethod::Post,
        path: "/api/node-agent/logs",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentMetrics,
        method: RouteMethod::Post,
        path: "/api/node-agent/metrics",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentSubscriptionClientUsageReport,
        method: RouteMethod::Post,
        path: "/api/node-agent/subscription-clients/{client_id}/usage",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentSubscriptionSessionsReport,
        method: RouteMethod::Post,
        path: "/api/node-agent/subscription-sessions/report",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
    RouteSpec {
        id: RouteId::NodeAgentSubscriptionSessionEnforcementResult,
        method: RouteMethod::Post,
        path: "/api/node-agent/subscription-sessions/enforcement-result",
        group: RouteGroup::NodeAgent,
        exposure: RouteExposure::NodeAgent,
        paginated: false,
    },
];

impl RouteId {
    /// The table row for this identifier.
    ///
    /// The panic is unreachable: `route_table_covers_every_route_id_exactly_once`
    /// guarantees every variant is present in `ROUTE_TABLE`.
    pub fn spec(self) -> &'static RouteSpec {
        ROUTE_TABLE
            .iter()
            .find(|spec| spec.id == self)
            .expect("ROUTE_TABLE covers every RouteId")
    }

    /// `"POST /api/nodes/{node_id}/auth/rotate"`, for documents that reference a
    /// route as text. Written from here rather than as a literal, otherwise such
    /// a document drifts from the router exactly as the contract's route list
    /// used to.
    pub fn endpoint_label(self) -> String {
        let spec = self.spec();
        format!("{} {}", spec.method.as_str(), spec.path)
    }
}

/// Routes with a given trust boundary, in table order.
pub fn routes_with_exposure(exposure: RouteExposure) -> impl Iterator<Item = &'static RouteSpec> {
    ROUTE_TABLE
        .iter()
        .filter(move |spec| spec.exposure == exposure)
}

/// The browser surface: exactly what the admin UI calls.
pub fn admin_ui_routes() -> impl Iterator<Item = &'static RouteSpec> {
    routes_with_exposure(RouteExposure::AdminUi)
}

/// Groups in order of first appearance, with their routes.
pub fn admin_ui_routes_by_group() -> Vec<(RouteGroup, Vec<&'static RouteSpec>)> {
    let mut grouped: Vec<(RouteGroup, Vec<&'static RouteSpec>)> = Vec::new();
    for spec in admin_ui_routes() {
        match grouped.iter_mut().find(|(group, _)| *group == spec.group) {
            Some((_, specs)) => specs.push(spec),
            None => grouped.push((spec.group, vec![spec])),
        }
    }
    grouped
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn route_table_covers_every_route_id_exactly_once() {
        let mut seen: Vec<RouteId> = ROUTE_TABLE.iter().map(|spec| spec.id).collect();
        assert_eq!(
            seen.len(),
            RouteId::ALL.len(),
            "ROUTE_TABLE has {} rows while RouteId has {} variants",
            seen.len(),
            RouteId::ALL.len()
        );
        for id in RouteId::ALL {
            let position = seen.iter().position(|candidate| candidate == id);
            match position {
                Some(index) => {
                    seen.remove(index);
                }
                None => panic!("{id:?} is declared in RouteId but absent from ROUTE_TABLE"),
            }
        }
        assert!(seen.is_empty(), "ROUTE_TABLE has surplus rows: {seen:?}");
    }

    #[test]
    fn route_table_has_no_duplicate_method_and_path() {
        let mut pairs = HashSet::new();
        for spec in ROUTE_TABLE {
            assert!(
                pairs.insert((spec.method, spec.path)),
                "duplicate {} {}: axum panics while building the router",
                spec.method.as_str(),
                spec.path
            );
        }
    }

    #[test]
    fn admin_ui_surface_excludes_node_agent_and_executor_routes() {
        for spec in admin_ui_routes() {
            assert!(
                !spec.path.starts_with("/api/node-agent/"),
                "{} leaked into the browser surface",
                spec.path
            );
        }
        let exposures: HashSet<RouteExposure> =
            admin_ui_routes().map(|spec| spec.exposure).collect();
        assert_eq!(
            exposures,
            HashSet::from([RouteExposure::AdminUi]),
            "the exposure filter let a foreign trust boundary through"
        );
    }

    #[test]
    fn every_node_agent_path_is_declared_as_node_agent_exposure() {
        for spec in ROUTE_TABLE {
            if spec.path.starts_with("/api/node-agent/") {
                assert_eq!(
                    spec.exposure,
                    RouteExposure::NodeAgent,
                    "{} serves the agent but is declared as {}",
                    spec.path,
                    spec.exposure.as_str()
                );
            }
        }
    }

    #[test]
    fn paginated_routes_are_read_only() {
        for spec in ROUTE_TABLE {
            if spec.paginated {
                assert_eq!(
                    spec.method,
                    RouteMethod::Get,
                    "{} is marked paginated but is not a read",
                    spec.path
                );
            }
        }
    }
}
